### ISSUE TITLE
Can't create account

### ISSUE THREAD

**Issue by ClarkeCC** [DHowett/spectre#73] opened 2017-07-03 22:33 UTC
I'm trying to create a account. When I fill in the username and password field, then hit the "Log In or Create Account" button it does nothing.

**Comment by DHowett** [comment] 2017-07-03 23:06
Duplicate of #43. Also, this is now fixed.

Thanks for your patience!

**Closed by DHowett** 2017-07-03 23:06 UTC

**Comment by ClarkeCC** [comment] 2017-07-05 14:54
@DHowett thank you!
