### ISSUE TITLE
Unable to create account (dark window)

### ISSUE THREAD

**Issue by WAZAAAAA0** [DHowett/spectre#43] opened 2016-09-29 01:42 UTC
Clicking the "Log In or Create Account" button turns the window grey and nothing happens.
https://i.imgur.com/BY68bdk.jpg

The main reason I wanted to use this paste service was because of the edit function and I can't use it since I have no access to accounts.

**Comment by DHowett** [comment] 2016-09-29 01:44
Thanks for reporting this.

You should be able to edit pastes even without an account, with the
restriction that you must edit a paste from the same browser used to create
it.

Once you're able to make an account and log in, every paste you created
will be associated with your new account.

**Comment by WAZAAAAA0** [comment] 2016-09-30 16:31
> with the restriction that you must edit a paste from the same browser used to create it

That's not an option for what I want. For example I just lost the ability to edit a test paste I made yesterday because my IP has probably changed in the meanwhile.

I just need the ability to occasionally edit the contents of a link long-term, and an account would provide me that. If the account system is for some reason broken beyond repair, it could be replaced with some "unique Edit/Delete link" system that doesn't require any, similar to justpaste.it and various file hosting services (random example: oceanhost.eu)

But I'm not complaining, this paste service is still the best one available for several good reasons:
- One of the few with SSL
- No ads (pastebin.com)
- No Flash Player (0bin.net)
- No CAPTCHA (paste.lisp.org)
- Pastes are private by default (even robots.txt cooperates)
- Simple high contrast white on black interface
- Not dead (pastie.org, pastebay.net)
- Open source

so, good job there.

**Comment by Siguza** [comment] 2016-10-21 14:55
I'm having the same issue, except I already have an account, but can't log in.

A quick view at my browser's dev tools show that the XHR request to `/auth/login` just hangs indefinitely.
It does not hang, however, when either of the username/password fields is left blank.
From that, and the fact that both account creation and login are affected, it looks to me like nothing comes beyond [this line](https://github.com/DHowett/ghostbin/blob/master/auth.go#L71):

    newuser := userStore.Get(username)

Any chance you could investigate this?

**Comment by DHowett** [comment] 2016-10-24 17:10
Sorry all; I haven't been able to reproduce either of these.

@WAZAAAAA0 Thanks! There are a couple things you could do to ameliorate the access situation.
* You don't need an account to keep editing pastes -- Ghostbin saves a token in a year-long session cookie. If you're not accepting cookies or clearing them at the end of every browsing session, this won't work particularly well for you.

  It shouldn't be tied to IP address. If you're seeing issues here, I'd love to give them a peek separately from this issue.

  Any pastes created under a session will automatically migrate to an account once you can register or log in.

* If you click the lemon icon in the top right of a paste you have access to and save the grant URL it gives you, you can use that for long-term access renegotiation. Each link is good for granting a single user or session the _grant+edit_ permission. These are persisted between server instances, so they should remain reasonably stable.

@Siguza This could perhaps be an intermittent Persona issue; are you using persona? I'm intending to replace it with something else before the [November 30th cutoff](https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers).

**Comment by Siguza** [comment] 2016-10-25 12:51
I'm using plain old username + pw.

When I enter something in the username and password fields and click "Log In or Create Account", an XHR gets sent that just hangs.
Below is a "cURL copy" of that request (obviously with fake username/pw):

    curl 'https://ghostbin.com/auth/login' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: https://ghostbin.com/' -H 'Origin: https://ghostbin.com' -H 'X-Requested-With: XMLHttpRequest' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.21 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' --data 'type=username&username=herp&password=derp&confirm_password=' --compressed

In Chrome, my tab usually becomes unresponsive after 5 minutes or so, but the console actually gave me a response after ca. 10 minutes:

    <h1>Proxy Error</h1>
    <p>The proxy server received an invalid
    response from an upstream server.<br />
    The proxy server could not handle the request <em><a href="/auth/login">POST&nbsp;/auth/login</a></em>.<p>
    Reason: <strong>Error reading from remote server</strong></p></p>
    <hr>
    <address>Apache/2.4.7 (Ubuntu) Server at ghostbin.com Port 443</address>

Does the above command work for you (i.e. return a response in reasonable time)?

**Comment by forfucksayk** [comment] 2016-10-27 00:47
same here, trying to create an account but encountering this problem.
don't let ghostbin die ;(

**Comment by Siguza** [comment] 2017-01-29 17:40
I can log in successfully again...

**Comment by WAZAAAAA0** [comment] 2017-01-30 11:58
Tried again today.

logins and logouts work, tested with the following account I luckily guessed:
ID:123456
PW:123456
Attempting to login ID 123456 with a different password will rightfully show the "invalid username or password" error.

On the other hand, attempting a registration will still make the window "darker", but this time for less than 1 second before returning to "regular white" with no error notification about anything.

**Comment by macks2008** [comment] 2017-03-09 01:02
oh good, I'm not the only one having trouble with the non-conventional login/account system.  there doesn't seem to be a way to reset my password, and I can't seem to create a new account (instead simply getting "invalid username/password". I imagine it would be valid if the account exists, hmm?)... What can I do?

**Comment by darkenvy** [comment] 2017-04-03 19:17
I have the same issue. The login pane flashes grey for a second and comes back. Idk if I created an account/logged in successfully now. Can we get some notification feedback?

PS: I anti-fingerprint. What is the fingerprinting method used to 'remember the browser'?

**Comment by DHowett** [comment] 2017-04-03 19:55
That 503 is very useful info; thanks!
Ghostbin uses a standard (secure-only, http-only) cookie to keep track of
your login.

**Comment by darkenvy** [comment] 2017-04-05 18:26
So I wanted to make sure I was allowing cookies. whitelisted this site on the adblock and checked cookies.
These are the 4 cookies I have:
_ga
_gat
authentication
session

Now I get a 502 error when it's POSTing.

> POST https://ghostbin.com/auth/login 502 (Proxy Error)

**Comment by celphtilted** [comment] 2017-04-09 10:00
will there be any fix to this problem? Logins will be much superior compared to the current cookie design. Please let us now if there will be a potential fix, because for the past 6 months, logins never worked and I don't see why there is no answer to this problem. If logins won't ever work, let us know about that. ;/

I just lost all the pastes that I shared with a friend of mine, we still have the cookies, but it does not let us edit the pastes for some reason.

**Comment by macks2008** [comment] 2017-04-29 22:46
come on Dustin. Help us out here? 😦

**Comment by oh1** [comment] 2017-07-01 23:14
I'm using your website because I want privacy, my browser deletes cookies when closed. Your solution does not work for everyone.

**Comment by DHowett** [comment] 2017-07-03 20:45
This may have been fixed by an emergency deploy today. Can you check?

If not, I've added additional logging to the user session setup/teardown flow.

**NOTE**: Ghostbin v1 is in maintenance mode; i've been putting most of my effort into spectre/ghostbin-v2, so it's fallen  by the wayside. I apologize for the inconvenience.

**Comment by DHowett** [comment] 2017-07-03 20:47
@oh1 I'm interested in your suggestions to make sessions and access rights preservation more seamless for end users who don't want cookies. I really do value privacy, and I'm trying to store as little data as possible.

Account usernames are discarded (but can, unfortunately, be rainbow-tabled since they're just a hash of the user's true name), and I go to great lengths to avoid storing any identifying information. Does that work for you? I can't look at who owns what pastes. Since your browser deletes cookies when you end your session, you'd have to log in every time... which might be what you want?

**Comment by DHowett** [comment] 2017-07-03 23:07
Finally root-caused this. A change in the accounts package panicked out for missing accounts (lol) before we wrote our response.

This has been broken for quite some time. 😣

**Comment by DHowett** [comment] 2017-07-03 23:07
@macks2008 v2 will sport account management.

**Closed by DHowett** 2017-07-03 23:07 UTC
