### ISSUE TITLE
API for interaction with external editor?

### ISSUE THREAD

**Issue by mg979** [DHowett/spectre#77] opened 2018-01-02 18:59 UTC
Hello, I'd like to write (try at least) a Sublime Text plugin that can create pastes on ghostbin, access your pastes, etc. Is there a way to achive this? It's my first try at writing this kind of things(that require web interactions), so I have no idea how to start it. If you can provide me some insights I could give it a try. Thanks for your wonderful paste service.

**Comment by DHowett** [comment] 2018-01-05 07:37
Hi @mg979! Thanks for the inquiry. Ghostbin doesn't have an API for anything but creating pastes right now, but it's planned as part of #61 and the v2 rewrites.

If you'd like to submit pastes, you can follow the guide [here](https://ghostbin.com/paste/p3qcy).

It may also be worth looking at the raw session list, `https://ghostbin.com/session/raw`, but that's not likely to work forever.

I'm closing this as a duplicate of #61, but feel free to move over there or reopen this with more questions!

**Comment by DHowett** [comment] 2018-01-05 07:38
Also, the (ship checklist)[https://gitlab.howett.net/Ghostbin/spectre/issues/76] might be interesting :)

**Closed by DHowett** 2018-01-05 07:37 UTC

**Comment by mg979** [comment] 2018-01-05 14:57
Ok thanks, I'll try to start doing something with it :)
